### ISSUE TITLE
Inquiry about "nicepath"

### ISSUE THREAD

**Issue by SiYeon-Ju** [EPFL-LCSB/nicepath#1]
Hello,

I hope this message finds you well. I am a student majoring in Biology at Ajou University. I came across your "nicepath" paper and attempted to clone the repository from GitHub to run it on my computer. However, I have two questions I'd like to inquire about.

Firstly, in the default Test folder, what does the number corresponding to target_compounds in source_compounds.txt and parameters.txt signify? It doesn't seem to be a KEGG Compound ID, such as Source Compound number C44, C93  and Target Compound number C53 for 3HP.

Secondly, regarding the R numbers in the Reaction_Entries column of the output file, what do they represent? Are they different from KEGG Reaction Numbers?

I understand you may have a busy schedule, but I would greatly appreciate it if you could provide some insights on these matters.

Thank you very much.

Best regards,

**Comment by jasminhafner** [comment]
Hi,

Firstly, in the default Test folder, what does the number corresponding to target_compounds in source_compounds.txt and parameters.txt signify? It doesn't seem to be a KEGG Compound ID.

The number corresponds to the compound entry number (column “ENTRY” of the COMPOUNDS sectioin) in the input file under ./data/Retrobio/’Test_compound’/systemFiile_’Test_compound’.txt (’Test_compound’ can be 3HP or Bisabolene, the example from the paper). When you clone the repository, make sure to also fetch the files in ./data. You might have to use the command “git lfs pull” for that, if it’s not cloned automatically.

Secondly, regarding the R numbers in the Reaction_Entries column of the output file, what do they represent? Are they different from KEGG Reaction Numbers?

The Reaction_Entries refer to the “ENTRY” column of the “REACTION” section in the input file, similar as compound numbers. For example, R1 refers to the reaction ENTRY 1 in the input file. Same for compounds - C1 would be compound unter ENTRY 1.

I hope this helps! :)

Best,
Jasmin

On 29 Nov 2023, at 06:42, SiYeonJu ***@***.***> wrote:



Hello,

I hope this message finds you well. I am a student majoring in Biology at Ajou University. I came across your "nicepath" paper and attempted to clone the repository from GitHub to run it on my computer. However, I have two questions I'd like to inquire about.

Firstly, in the default Test folder, what does the number corresponding to target_compounds in source_compounds.txt and parameters.txt signify? It doesn't seem to be a KEGG Compound ID.

Secondly, regarding the R numbers in the Reaction_Entries column of the output file, what do they represent? Are they different from KEGG Reaction Numbers?

I understand you may have a busy schedule, but I would greatly appreciate it if you could provide some insights on these matters.

Thank you very much.

Best regards,

**Comment by SiYeon-Ju** [comment]
Thank you very much, good day!
